version: '3'
services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - graylog-network
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - graylog-network
    restart: always

  graylog:
    image: graylog/graylog:4.3
    container_name: graylog
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordthatislongenough1234567890
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://192.168.1.151:9000/
      - GRAYLOG_GELF_UDP_PORT=12201
    ports:
      - "9000:9000"   # Web interface
      - "12201:12201/udp"  # GELF UDP input
      - "514:514/udp"  # Syslog UDP (optional)
    depends_on:
      - mongodb
      - elasticsearch
    volumes:
      - graylog_data:/usr/share/graylog/data
    networks:
      - graylog-network
    restart: always

networks:
  graylog-network:
    driver: bridge

volumes:
  mongodb_data:
  elasticsearch_data:
  graylog_data: